### ISSUE TITLE
Emails: "Click here to unsubscribe." is missing the link to the unsubscribe page

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#145]

**Comment by adrianosvaldomartinez** [comment]
HI! @yolile where should that link point to?

**Comment by yolile** [comment]
It should link to the same page as the "Remove me" button

**Comment by adrianosvaldomartinez** [comment]
as is its now, the "remove me" button allows users to decline, and is only allowed for applications that havent been accepted yet. 
Should it be allowed to decline an application that has been already submited-accepted ?
i ask because some of the email templates that have the unsuscribe link are sent when the application is already accepted.

**Comment by yolile** [comment]
> Should it be allowed to decline an application that has been already submited-accepted ?

No. In that case, let's remove the "Click here to unsubscribe" text from all the templates.

**Comment by adrianosvaldomartinez** [comment]
ok
