### ISSUE TITLE
Define Entity-Relationship Diagram

### ISSUE THREAD

**Issue by nahu** [open-contracting/credere-backend#37]
The document proposed
https://docs.google.com/document/d/1Vs8eAexAs4havMabmg3UdjQbWro4CJ2q0rgdAVyBmAg/edit?usp=sharing

**Comment by yolile** [comment]
With @jpmckinney, we reviewed the proposal and have some comments, questions, and recommendations:

**Constraints**:

- Are there any additional constraints on any tables (other than the primary key)?
- All TEXT should be NOT NULL, and should be set to “” by default. Otherwise, we have two values for empty (NULL and “”) and this makes the logic more complicated. ([ref](https://docs.djangoproject.com/en/3.2/ref/models/fields/#null))
- All JSONB should be NOT NULL, and should be set to the appropriate default (e.g. {}). Otherwise, we have two values for empty, and this makes the logic more complicated.
- It is possible for the data sources to have incomplete data (e.g. no contractperiod_startdate), so these columns (if not TEXT) must be nullable.
- Also, the product requirements allow FIs and OCP admins to fill in missing data. Manually entered data must be indicated. How will this indicator be determined?
- expires_at should be nullable. When the application is with the FI, the timer stops for the MSME (NULL). The MSME is only on the clock when the application is in Pending, Accepted, and Awaiting Information states.

**Table and column names suggestions:**

- msme -> borrower (both in table and column names)
- fi -> lender (both in table and column names)
- award.tender_title -> title (the title might come from different fields in other countries)
- award.award_description -> description (same reason as for title)
- award.secop_url -> source_url
- award.cpd_value -> budget_value
- application.contact_submitted_amount -> contract_amount_submitted
- application.requested_amount -> amount_requested
- application.amount_currency -> currency
- application.repaiment_months -> repayment_months
- application.submitted_at -> borrower_submitted_at
- application.fi_aprove_data -> lender_approved_data
- application.declined_data -> lender_rejected_data (MSMEs “decline” using Credere, and FIs “reject” applications)
- msme.full_address -> address
- msme.national_tax_id -> legal_identifier
- msme.type -> size
- msme.registration_type -> type
- statistic.process_at -> updated_at

**New columns:**

- Add a msme.legal_identifier_type TEXT column.
- Add an award.source_data JSONB column, with the original data from which the fields were extracted, for debugging/auditing purposes.
- Add an application.declined_reason TEXT column as per [SME_S3_declined_question_2 design](https://drive.google.com/file/d/1q9gsZ20hliwsRnmnDBMPVGZC-Y9IN-NR/view?usp=sharing)
- Add an application.archived_at TIMESTAMP column. This is to represent the Cancelled state (“cancelled” meant confidential data has been deleted).
- Add one date column for each relevant application status in the application table:

  - created_at 
  - borrower_accepted_at
  - borrower_submitted_at
  - lender_started_at
  - lender_approved_at (new)
  - borrower_uploaded_contract_at (new)
  - final_status_at (new)

**Column changes:**

* msme.country -> Remove column.
    * We don’t know yet if in the future we will deploy Credere as a single multi-country deployment, or as one deployment per country.
* award.legal_entity_type_detail -> Remove column.
    * This column has the same semantics as msme.registration_type – unless there was a reason for including it in both tables?
* msme.status (text) rename and change type to msme.declined_at (timestamp)
    * Track the date, in case we want to re-contact the MSME, e.g., after a major change to how Credere functions / what it offers.

**Column types. Use:**

* integer instead of bigint (we will not be exceeding 2 billion)
* decimal instead of double (to avoid floating point imprecision)

**Enumeration changes:**

* award.status: Does award.status = “declined” mean the same thing as application.stage = “declined”? If so, remove “declined”. Since that leaves only “active” and “previous”, we suggest changing “status” to a “previous” BOOLEAN column.
* application.status: “Started by MSME”, “Pending Primary Email Confirmation” and “Pending Documents” can be true at the same time. We suggest moving the two “Pending X” to boolean columns. That leaves "Pending", "Started by MSME" and "Submitted MSME", which are repetitive with application.stage. We suggest removing the status column, and renaming “stage” to “status”.
* Application.stage:
    * Rename:
        * active -> accepted
        * in progress -> started

**Comment by yolile** [comment]
Also, for the awards-related information, please refer to this updated [table](https://docs.google.com/document/d/1ZtHcZKJfp9HIxa6HR6o1SrzTJ7schu4Pu8vGdFToSVA/edit#heading=h.berhpbhz9vzx)

**Comment by yolile** [comment]
And see the comments about hash columns at https://github.com/open-contracting/credere-backend/issues/10#issuecomment-1544501066:

> Add a hashed id column in the MSME table using the MSME identifier
Add a hashed id column in the application table using the MSME identifier and the award identifier

**Comment by nahu** [comment]
The document was updated with all names suggestions and updated data types as well.

We also added the **id\_contract**, **source\_last\_updated\_at** and **entity\_code** fields to the **award** table specified in the _Colombia CCE data access_ document, and the hash column identifiers proposed in #10

- **borrower\_identifer** hashed id column using the MSME identifier (legal\_identifier)
- **award\_borrower\_identifer** hashed id column using the MSME identifier (legal\_identifier) and the award identifier (id\_contract)

Removed NOT NULL for **award\_id** in the award table.

## Clarifications

- Are there any additional constraints on any tables (other than the primary key)?

Yes, in the diagrams, all fields ended with **\_id** are foreign keys. **name** in lender, **uuid** in award and **borrower\_identifier** in borrower, should be unique. **award\_borrower\_identifer** could have duplicate values when an MSME when there are still credit options available for a rejected application.

- Also, the product requirements allow FIs and OCP admins to fill in missing data. Manually entered data must be indicated. How will this indicator be determined?

We will handle this in the application\_action table, setting the type to _Award Update_ and saving in the field **data** the updated field name and value, the same for the borrower updates with the type _Borrower Update._ The updated document has examples of this.

- Add an application.declined\_reason TEXT column as per [SME\_S3\_declined\_question\_2 design](https://drive.google.com/file/d/1q9gsZ20hliwsRnmnDBMPVGZC-Y9IN-NR/view?usp=sharing)

We have added a new field **borrower\_declined\_data,** used to save the reasons for declination — examples of this in the document.

- award.status: Does award.status = “declined” mean the same thing as application.stage = “declined”? If so, remove “declined”. Since that leaves only “active” and “previous”, we suggest changing “status” to a “previous” BOOLEAN column.

It was meant to denote that the MSME declined the application for this currently active award. Still, we can turn this to _previous = true_ and have the information for the declination in the application.

- application.status: “Started by MSME”, “Pending Primary Email Confirmation” and “Pending Documents” can be true at the same time. We suggest moving the two “Pending X” to boolean columns. That leaves "Pending", "Started by MSME" and "Submitted MSME", which are repetitive with application.stage. We suggest removing the status column, and renaming “stage” to “status”.

Added **pending\_documents** and **pending\_email\_confirmation** to application table

- **pending\_documents** when MSME needs to upload documents before the application submission
- **pending\_email\_confirmation** when MSME changes the primary email address

Removed **status** and renamed **stage** to **status**, enum values updated with the new flow in #39. Here it was suggested to change _In Progress_ to _Started_, but in #39 _In Progress_ remains; which one do we use? @yolile

**Comment by yolile** [comment]
> Here it was suggested to change In Progress to Started, but in https://github.com/open-contracting/credere-backend/issues/39 In Progress remains; which one do we use? @yolile

"Started", thanks for pointing it out, I will update the diagram once more

**Comment by yolile** [comment]
> We also added the id_contract, source_last_updated_at and entity_code fields to the award table specified in the Colombia CCE data access document, and the hash column identifiers proposed in https://github.com/open-contracting/credere-backend/issues/10

As per this document, for `award`, please add:
-  `procurement_method`
- `contracting_process_id`
- `procurement_category` (for tipo_de_contrato)

For `award`, remove:
- `planning_rationale`
- `legal_entity_type_detail`
- `budget_value`
- `valid_balance`

Move `source_url` from `borrower` to `award`

Rename `id_contract` to `source_contract_id`

**Comment by yolile** [comment]
For the JSONB columns, it is fine to leave them as they are for now, and we can recheck if we need non-JSONB columns/tables when we clarify the requirements more.

**Comment by nahu** [comment]
The document has been updated with the missing fields. It only remains to update #39 with the change of the enum value "Awaiting Information" to "Information Requested" suggested by James
