### ISSUE TITLE
Track if borrowers are clicking the button with the link to the external onboarding system

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-backend#435]
Currently, the button is just a button with a href with `lender.external_onboarding_system_url`.

@jpmckinney any preferences or ideas on how to implement this? 

It could be a new `ApplicationAction` or a new field e.g. `borrower_accessed_external_onboarding_system_at`

**Comment by jpmckinney** [comment]
I guess my thought would be: Are we reporting on this value? If so, that's easier to calculate if stored on the Application (e.g. filter by status and then see how long it's been for each borrower, so that we know whether to bother the lender about reporting back to us).

Either way, it can be an Action on top of that. For me ApplicationActionType has become a bit of a [Chesterton's Fence](https://theknowledge.io/chestertons-fence-explained/); I don't know exactly why we have it, but as long as we have it, we might as well use it to track all actions.

**Comment by yolile** [comment]
> I don't know exactly why we have it

It was part of the original user requirements.

> filter by status 

Hmm, I'm not sure if we should add a new status, as we can't ensure the borrower is indeed doing the onboarding process, we can only ensure they have clicked the button at some point (that is why I'm suggesting a date field instead). But I'm also fine with a new status.

**Comment by jpmckinney** [comment]
I just mean we might filter by "SUBMITTED" or "STARTED" and then check which of those borrowers clicked the link.

**Comment by yolile** [comment]
Cool, so are you fine with the new `Application.borrower_accessed_external_onboarding_system_at` field?

**Comment by jpmckinney** [comment]
Yup! And I figure we would add a corresponding action type for consistency?

**Comment by yolile** [comment]
Sure!
